### ISSUE TITLE
k.indexOf is not a function

### ISSUE THREAD

**Issue by liukai-lk** [InCar/ali-mns#14]
use sendP method, encounter issue: k.indexOf is not a function,
`for (var i in keys) {
                  var k = keys[i];
                  if (k.indexOf("x-mqs-") === 0) {
                      mqsHeaders += Util.format("%s:%s\n", k, headsLower[k]);
                  }
              }`

**Comment by AceBear** [comment]
d2dbbbf391b6ea5075069efac6999e31b2582665

**Comment by liukai-lk** [comment]
解决了，谢谢

**Comment by AceBear** [comment]
2.3.9 has been released to npm few minutes ago.
https://www.npmjs.com/package/ali-mns
