### ISSUE TITLE
向主题队列发布消息时支持KeepAlive

### ISSUE THREAD

**Issue by AceBear** [InCar/ali-mns#21]
[ali-mns@2.6.0](https://github.com/InCar/ali-mns/releases/tag/2.6.0)开放了底层的[request](https://www.npmjs.com/package/request#requestoptions-callback)选项给`Topic.publishP`方法. 
参见 e1f649391f94f24794aa8c78d1ab1c0c6850b33e

给第5个参数`options`传入`{ forever: true }`,即可开启*keepAlive*
```js
// ...
topic.publishP("Hello", false, null, null, { forever : true });
// ...
```
[sample](https://github.com/InCar/ali-mns/blob/e1f649391f94f24794aa8c78d1ab1c0c6850b33e/test/topic.js#L97)

更多request支持的选项参见 https://www.npmjs.com/package/request#requestoptions-callback

@daizisheng

**Comment by daizisheng** [comment]
太赞了
