### ISSUE TITLE
能否在 recvP 中提供选项关闭 Base64 解密

### ISSUE THREAD

**Issue by netputer** [InCar/ali-mns#22]
我在项目中使用了阿里云 MNS 的主题，并创建了订阅，推送到队列。队列里的 MessageBody 都是没有被 Base64 加密的，却被强行解密，导致内容变得面目全非，尝试 Base64 加密回去，也得不到原来的内容。

**Comment by AceBear** [comment]
你能提供示例代码吗？

因为主题Topic根本就不支持recvP()方法
![image](https://cloud.githubusercontent.com/assets/5030312/21931194/103f3e94-d9d5-11e6-9e4e-157373628915.png)

**Comment by AceBear** [comment]
曾经想加上，但遇到一些困难，只好放弃了这个想法

1. 阿里云底层是用xml来通信的,参见这里(https://help.aliyun.com/document_detail/35134.html?spm=5176.product27412.6.686.5IkMSC),如果不使用base64编码,那么能发送的字符非常有限,新手如果不知道这个特点,很容易就会在其中包含特别的字符(比如尖括号,中文字符)使得xml不再合法,这时报出来的错很奇怪,非常难以调试.

2. 如果增加这个选项，那么发送和接收必须在运行时保持一致，对于一个小型工程来说，这不算什么问题，但考虑到使用上了MNS这么复杂的中间件，通常都面向大型的开放工程，通信很有可能在多个(很有可能不止2个)端点发生，保持它们一致就会不那么容易。于是，这里替代最终用户做了这个决定，所有的通信都使用base64编码。

3. 如果要增加这个base64选项，还需要增加2个子功能
    - 发送前置一个合法字符集校验,以避免发送了尖括号,中文这样的内容,使得发送失败,而得到很奇怪的错误
    - 接收前置一个base64识别器,自动识别发送的是原始内容还是base64编码内容,避免最终用户手动保持发送接收一致.

4. 对于你遇到的问题,有几个方案
    - 最简单 base64编码并不复杂,研究一下[MQ.ts#L49](https://github.com/InCar/ali-mns/blob/e1f649391f94f24794aa8c78d1ab1c0c6850b33e/ts/MQ.ts#L49),就可以搞定它。
    - fork or clone本工程，修改一下[MQ.ts#L145-L153](https://github.com/InCar/ali-mns/blob/e1f649391f94f24794aa8c78d1ab1c0c6850b33e/ts/MQ.ts#L145-L153)
    - 如果你有时间，实现3里提到的内容，发个PR给我，我把它们加到下一个版本里
