### ISSUE TITLE
关于使用topic.publishP 中使用message填写attrs 值错误

### ISSUE THREAD

**Issue by jmcatvltx2150** [InCar/ali-mns#24]
var attrs ={  DirectSMS:{
           FreeSignName:“XXXXXXXXXXXXXXXXXXXXXXXX”,
           Receiver:“XXXXXXXXXXXXXXXXX”,
           TemplateCode:“XXXXXXXXXXXXXX”,
           Type:"singleContent",
           SmsParams:{code: "125855",product:"XXXX"}
        }}
attrs 输入上述数据返回 The Content-MD5 you specified is invalid. 异常，如果为null 可以正常使用，想问一下是不支持DirectSMS 还是attrs 格式，我没看attrs 格式列子

**Comment by AceBear** [comment]
确实还不支持
杂事较多，给我3天时间，抽空支持上

**Comment by AceBear** [comment]
需要提交一些信息才能申请FreeSignName，暂时我不方便自己测试
试试下面这种写法，看看是否奏效？

```javascript
var directSMS = {
    FreeSignName: "XXXXXXXXXXXXXXXXXXXXXXXX",
    TemplateCode: "XXXXXXXXXXXXXX",
    Type: "singleContent",
    Receiver: "XXXXXXXXXXXXXXXXX",
    SmsParams: { code: "125855", product: "XXXX" }
};

var attrSMS = {
        DirectSMS: JSON.stringify(directSMS)
};

topic.publishP("HelloSMS", false, null, attrSMS);
```

**Comment by yeliex** [comment]
@AceBear JSON.stringify 还是一样

**Comment by yeliex** [comment]
FreeSignName会有存在中文的情况 此时就会出现签名不正确

**Comment by yeliex** [comment]
对中文内容单独转义后 md5 能过了 然后加上JSON.stringify, 数据格式对照文档ok,请求返回`The XML you provided did not validate against our published schema, cause by "DirectSMS" Element. `

**Comment by AceBear** [comment]
我这里也是报这个错
```
The XML you provided did not validate against our published schema, cause by "DirectSMS" Element.
```
还没搞明白是啥原因

**Comment by yeliex** [comment]
@AceBear 开了阿里工单 说是DirectSMS要单独JSON.stringify
现在新问题来了 签名中文的时候 MD5校验是错误的 如果用encodeURIComponent()转义 会报InvalidSignName.Malformed

**Comment by yeliex** [comment]
```
topic.publishP('varifycode', false, null, {
  DirectSMS: JSON.stringify({
    FreeSignName: encodeURIComponent('签名'),
    TemplateCode: 'SMS_60190063',
    Type: 'singleContent',
    Receiver: '15900000000',
    SmsParams: JSON.stringify({
      code: '123456',
      product: 'test'
    })
  })
})
```

**Comment by yeliex** [comment]
如果SmsParams中有中文也是如此

**Comment by jmcatvltx2150** [comment]
@yeliex 我想问一下，按照你的方式验证是过了，给阿里云发送消息也没有返回错误，但控制台没有信息和手机也没收到短信，但我使用C#官方sdk就没有这种问题，是不是缺少了什么？？

**Comment by yeliex** [comment]
@jmcatvltx2150 错误信息是回调给你的 可能就是签名中有中文 因为转义后的签名 是对不上的 我至今没解决这个问题

**Comment by yeliex** [comment]
@jmcatvltx2150 要想正常使用 需要改sdk 去掉content-md5 然后会报xml格式错误 解决这个问题 就可以正常了 在postman里面测试能过 node里面一直有问题

**Comment by yayanyang** [comment]
@jmcatvltx2150 发了工单，说是要UTF-8编码。我估计是encodeURIComponent 这个东西不能这么用

**Comment by ethanzhanxd** [comment]
朴灵昨天写了一个包解决了这个问题。
https://github.com/aliyun/aliyun-mns-nodejs-sdk

**Comment by yayanyang** [comment]
所有的问题都是因为这段代码，在计算中文长度的时候出错了：
```js
if (!headers["Content-Length"]) headers["Content-Length"] = body.length;
```

我将它替换为：

```js
if (!headers["Content-Length"]) headers["Content-Length"] = new Buffer.Buffer(body, 'utf-8').length;
```

解决了这个问题，我没有仔细去查看其它的代码是否也有同样的问题。我估计应该很多。

**Comment by AceBear** [comment]
@yayanyang  你能把Content-Length相关修订发一个PR给我吗？

**Comment by thibetabc** [comment]
@yayanyang @AceBear @yeliex 
我替换成
if (!headers["Content-Length"]) headers["Content-Length"] = new Buffer.Buffer(body, 'utf-8').length;
并没有解决UTF-8编码问题
短信依然没有收到
请问你们最后怎么解决的

**Comment by thibetabc** [comment]
@jmcatvltx2150 你解决了？

**Comment by jmcatvltx2150** [comment]
我试过，修改if (!headers["Content-Length"]) headers["Content-Length"] = new Buffer.Buffer(body, 'utf-8').length; 可以收到短信，改为这个之后，签名可以使用中文，不需要转义了

**Comment by thibetabc** [comment]
@jmcatvltx2150 
我尝试了所有方法，依然收不到短信。可以加qq 603702750 沟通一下吗？感激不尽~~

**Comment by thibetabc** [comment]
问题已解决，成功接收到短信，修改了2处地方：

1、解决兼容中文，修改代码：
if (!headers["Content-Length"])
{
	headers["Content-Length"] = new Buffer.Buffer(body, 'utf-8').length;
}

2、解决md5签名，修改代码：
Account.prototype.b64md5 = function (text) 
{
	var cryptoMD5 = CryptoA.createHash("md5");
	return cryptoMD5.update(new Buffer.Buffer(text, 'utf-8')).digest('base64');
};


请求短信代码：
var AliMNS = require("ali-mns");
var aliCfg = {
    accountId:"123456789",//阿里主题中Endpoint的ID http(s)://123456789.mns.cn-hangzhou.aliyuncs.com/  
    keyId: "LTAIxxxxxxxrbpQvR",//阿里消息服务所用的密钥ID
    keySecret: "XFiQXps9Cxxxxxxxk1hUVgKM",//阿里消息服务所用的密钥值
    topicName: "sms.topic-cn-hangzhou",//阿里消息服务主题名称
};
var attrs = {
    DirectSMS: JSON.stringify(
        {
            FreeSignName:"短信签名",//短信签名
            TemplateCode:"SMS_123456",//短信模板
            Type:"singleContent",//单发
            Receiver:"13412345678",//接收人的手机号
            SmsParams:JSON.stringify({name:"123456"}),//短信具体参数: key为短信模板->短信内容的key
        }
    )
};
var account = new AliMNS.Account(aliCfg.accountId, aliCfg.keyId, aliCfg.keySecret);
var mns = new AliMNS.Topic(aliCfg.topicName, account);
mns.publishP("ali-mns",true,null,attrs).then(console.log, console.error);


感谢以上同学! @all

**Comment by AceBear** [comment]
@thibetabc 如果你有时间，不妨提交一个Pull Request过来，我把你的修改并入下一个修订版本里去

**Comment by thibetabc** [comment]
@AceBear 已PR

**Comment by AceBear** [comment]
aa389a9e64b480de04cb373dfdcc5d1f3f9d0fe4
#27
