### ISSUE TITLE
阿里短信发送失败

### ISSUE THREAD

**Issue by daileimail** [InCar/ali-mns#26]
最新的阿里短信得通过mq来发 但是sdk好像有坑
贴上代码
var account = new AliMNS.Account(accountId, accessKeyID, accessKeySecret);
    var topic = new AliMNS.Topic("sms.topic-cn-hangzhou", account, "hangzhou");
    // send message
    var params = JSON.stringify({
        FreeSignName: config.get('ali.smsSignName'),
        TemplateCode: config.get('ali.smsTemplateCode'),
        Type: 'singleContent',
        Receiver: phone,
        SmsParams: {
            code,
        }
    })

    //params =
    console.log(params)
    return topic.publishP("content", false, null, {DirectSMS: params});
}

**Comment by luckylh** [comment]
same here, 错误信息
```
{ Error:
   { '$': { xmlns: 'http://mns.aliyuncs.com/doc/v1' },
     Code: 'InvalidDigest',
     Message: 'The Content-MD5 you specified is invalid.',
     RequestId: '58F5C708449421603DEDE793',
     HostId: 'http://1888287682739631.mns.cn-hangzhou.aliyuncs.com' } }
```

**Comment by jmcatvltx2150** [comment]
存在一些问题，可以进行修改进行处理 https://github.com/InCar/ali-mns/issues/24

**Comment by AceBear** [comment]
aa389a9e64b480de04cb373dfdcc5d1f3f9d0fe4
