### ISSUE TITLE
Please update module universal-analytics because of the deprecated module node-uuid

### ISSUE THREAD

**Issue by anti-peng** [InCar/ali-mns#32]
See here [universal-analytics](https://github.com/peaksandpies/universal-analytics/pull/65), 

> The old module which was available by the name node-uuid got deprecated and will show error message upon every install of the module.

So update module universal-analytics will solve the problem 'Cannot find module node-uuid'.

**Comment by AceBear** [comment]
updated in 1cee88870431d023cf39847120255004d482f44c

**Comment by anti-peng** [comment]
Great job! Thanks.
