### ISSUE TITLE
recvP timeout bug

### ISSUE THREAD

**Issue by gfzhx** [InCar/ali-mns#4]
We use ali-mns in our projects, and create many MQ instances to receive messages from mns. we found that about 10 instances created, we did not receive any messages and we sure some message in mns's none activity status, We found the recvP function use 5 seconds timeout to avoid NetworkBroken error, but many instances receive message in same time will be block some times,so timeout error throw before message returned. I suggest that use request timeout to avoid NetworkBroken error , just in OpenStack.prototype.sendP function add {timeout : 20 * 1000} to var req and delete timeout.

**Comment by AceBear** [comment]
Thansk for your feedback, I'm studying the `timeout` feature of `request`.

**Comment by AceBear** [comment]
df8ba4e4c69b7aa50a4bc97858c64be50603143f
I have modified the timeout mechanism. 
Now it use the options.timeout of `Request`.

And there're 2 new methods can be used to adjust the timeout tolerance behavior.
[setRecvTolerance & getRecvTolerance](https://github.com/InCar/ali-mns#getrecvtolerance--setrecvtolerancevaluenumber)

**Comment by AceBear** [comment]
I have written a test to perform the similar process of yours.
1. Create 20 queues
2. Send 2000 messages to queues randomly.
3. Receive all of them.
4. Destroy queues.

The test code can be found in [$/test/performance.js](https://github.com/InCar/ali-mns/blob/master/test/performance.js)

A sample test log file is also provided in [$/test/performance.js](https://github.com/InCar/ali-mns/blob/6629a514d90dded6af1db31502628ab915144785/test/performance.log)

In the log, queue-12 received an message at 02'31" [$/test/performance.log#L1963](https://github.com/InCar/ali-mns/blob/6629a514d90dded6af1db31502628ab915144785/test/performance.log#L1963), 
then a timeout occurred in 02'42" [$/test/performance.log#L2062-L2064](https://github.com/InCar/ali-mns/blob/6629a514d90dded6af1db31502628ab915144785/test/performance.log#L2062-L2064), 
but it issued a retry immediately, and succeeded receiving left messages

You can change [these 3 arguments](https://github.com/InCar/ali-mns/blob/6629a514d90dded6af1db31502628ab915144785/test/performance.js#L30-L32) freely to do more test on it.

The `mocha` npm module is required to perform the test.
```SHELL
npm install -g mocha
mocha
```
