### ISSUE TITLE
Feature: support of topic/pubsub model

### ISSUE THREAD

**Issue by drahnieR** [InCar/ali-mns#8]
As the topic/pubsub model is now available in MNS. Is there any plan to support that?

**Comment by AceBear** [comment]
Have a nice tomb-sweeping day~~

I'm going to start learn the new topic model
![topic model](https://img.alicdn.com/tps/TB1VAtwMXXXXXbcXXXXXXXXXXXX-715-420.png)

**Comment by AceBear** [comment]
参见这个分支 [`dev-topic`](https://github.com/InCar/ali-mns/tree/dev-topic) :
大部分的功能已经实现了,文档稍后更新
示例先参考测试中的 [topic.js](https://github.com/InCar/ali-mns/blob/4049525020aa97720ca884a554a05d04d2bc8c60/test/topic.js)

+ AliMNS.MNSTopic 它取代原先的AliMNS.MNS, 增加了3个方法
    + listTopicP(prefix?:string, pageSize?:number, pageMarker?:string)
    + createTopicP(name:string, options?:any)
    + deleteTopicP(name:string)

+ AliMNS.Topic 主要的topic功能
    + getAttrsP()
    + setAttrsP(options:any)
    + listP(prefix?:string, pageSize?:number, pageMarker?:string)
    + subscribeP(name:string, endPoint:string, notifyStrategy?:string, notifyContentFormat?:string)
    + unsubscribeP(name:string)
    + publishP(msg:string)

+ AliMNS.Subscription
    + getAttrsP()
    + setAttrsP(options:any)

+ index.js文件还没有更新,暂时需要用`gulp`从`*.ts`文件生成一下

**Comment by drahnieR** [comment]
Xuan Ku !
